sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t eyallupu/healthcheck-webserver .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push eyallupu/healthcheck-webserver:latest;
    fi
